name: Build and Deploy Microservices

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-scan-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth, product, cart, order]
    defaults:
      run:
        working-directory: services/${{ matrix.service }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: |
          if [ -f .eslintrc.js ] || [ -f .eslintrc.json ]; then npm run lint || true; fi

      - name: Run tests
        run: npm test

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/${{ matrix.service }}-service:${{ github.sha }} .

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@v0.16.0
        with:
          image-ref: ghcr.io/${{ github.repository_owner }}/${{ matrix.service }}-service:${{ github.sha }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/${{ matrix.service }}-service:${{ github.sha }}

      - name: Update K8s manifests (placeholder)
        run: echo "Update manifests with new image tag here"

      - name: Trigger ArgoCD sync (placeholder)
        run: echo "Trigger ArgoCD sync here"
